server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # Since it's a registry, not a client
    fetch-registry: false         # It doesn't fetch other services
