server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

        - id: billing-service
          uri: http://localhost:8082
          predicates:
            - Path=/billing/**
          filters:
            - RewritePath=/billing/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
